### ISSUE TITLE
无法在build.gradle中添加如下引用导入项目

### ISSUE THREAD

**Issue by AutomaticCoding** [WGwangguan/SeparatedEditText#1]
在build.gradle中添加：
compile 'com.github.WGwangguan:SeparatedEditText:v1.0'

报错：Failed to resolve: com.github.WGwangguan:SeparatedEditText

**Comment by WGwangguan** [comment]
需要在根目录文件配置
```
maven { url "https://jitpack.io" }
```

具体可查看README，已更新
