### ISSUE TITLE
implementation 无法使用

### ISSUE THREAD

**Issue by Satsna** [WGwangguan/SeparatedEditText#2]
maven { url "https://jitpack.io" }已添加
但是  implementation 'com.github.WGwangguan:SeparatedEditText:Tag'依然不能引入.麻烦更新下

**Comment by WGwangguan** [comment]
tag处用当前版本替换就可以了，当前版本是"v1.2"
 implementation 'com.github.WGwangguan:SeparatedEditText:v1.2'

**Comment by Satsna** [comment]
非常感谢.有个不情之请啊!

**Comment by Satsna** [comment]
非常感谢.有个不情之请啊!输入中的下划线能不能高亮显示?O(∩_∩)O哈哈~

**Comment by Satsna** [comment]
![image](https://user-images.githubusercontent.com/28588015/50441973-f59bf200-0937-11e9-997c-e278e991307a.png)
